#### 4.5.2 ニューラルネットワークに対する勾配

In [3]:
import sys, os
import numpy as np

In [9]:
# 別ファイルから読み込み
from common.functions import softmax, cross_entropy_error
from common.gradient import numerical_gradient

In [12]:
class simpleNet:
    def __init__(self):
        self.W = np.random.randn(2, 3)
        
    def predict(self, x):
        return np.dot(x, self.W)
    
    def loss(self, x, t):
        z = self.predict(x)
        y = softmax(z)
        loss = cross_entropy_error(y, t)
        
        return loss

In [19]:
net = simpleNet()
print(net.W)

[[-0.99592744  0.77666535 -1.52068323]
 [-0.03256175  0.5215709  -0.53932784]]


In [20]:
x = np.array([0.6, 0.9])
p = net.predict(x)
print(p)

[-0.62686204  0.93541302 -1.397805  ]


In [21]:
np.argmax(p)

1

In [23]:
t = np.array([0, 0, 1])
net.loss(x, t)

2.6006782690367976

In [28]:
def f(W):
    return net.loss(x, t)

In [29]:
f = lambda w: net.loss(x, t) # defと同等の処理
dW = numerical_gradient(f, net.W)
print(dW)

[[ 0.09627362  0.45919245 -0.55546607]
 [ 0.14441043  0.68878867 -0.8331991 ]]
